# replace suo with other namespace
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: suo
  namespace: suo
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: suo
  namespace: suo
subjects:
  - kind: ServiceAccount
    name: default
    namespace: suo
roleRef:
  kind: ClusterRole
  name: suo
  apiGroup: rbac.authorization.k8s.io
